-- -----------------------------------------------
-- Group: Group 31 (Mario Godinez Gonzalez, Thai-Binh Guerreiro)
-- Assignment: Project Step 2
-- Creates all tables and constraints for the database schema.
-- Date: 2/4/26
-- -----------------------------------------------


-- Table creation generated by MySQL Forward Engineering, modified by Thai


SET FOREIGN_KEY_CHECKS=0;
SET AUTOCOMMIT = 0;



-- Table Customers

DROP TABLE IF EXISTS Customers ;

CREATE TABLE Customers (
  customer_ID INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  phone_number VARCHAR(15) NOT NULL,
  PRIMARY KEY (customer_ID)
)
ENGINE = InnoDB;



-- Table Orders

DROP TABLE IF EXISTS Orders ;

CREATE TABLE Orders (
  order_ID INT NOT NULL AUTO_INCREMENT,
  date DATETIME NOT NULL,
  customer_ID INT NOT NULL,
  PRIMARY KEY (order_ID),
  FOREIGN KEY (customer_ID)
  REFERENCES Customers (customer_ID)
  ON DELETE CASCADE
  ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- Table Suppliers

DROP TABLE IF EXISTS Suppliers ;

CREATE TABLE Suppliers (
  supplier_ID INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (supplier_ID)
)
ENGINE = InnoDB;



-- Table Product_Types

DROP TABLE IF EXISTS Product_Types ;

CREATE TABLE Product_Types (
  category_ID INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY (category_ID)
)
ENGINE = InnoDB;



-- Table Products

DROP TABLE IF EXISTS Products ;

CREATE TABLE Products (
  product_ID INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(6,2) NOT NULL,
  supplier_ID INT NOT NULL,
  category_ID INT NOT NULL,
  PRIMARY KEY (product_ID),
  FOREIGN KEY (supplier_ID)
    REFERENCES Suppliers (supplier_ID)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  FOREIGN KEY (category_ID)
    REFERENCES Product_Types (category_ID)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- Table Order_has_Products

DROP TABLE IF EXISTS Order_has_Products ;

CREATE TABLE Order_has_Products (
  order_ID INT NOT NULL,
  product_ID INT NOT NULL,
  quantity INT NOT NULL,
  PRIMARY KEY (order_ID, product_ID),
  FOREIGN KEY (order_ID)
    REFERENCES Orders (order_ID)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  FOREIGN KEY (product_ID)
    REFERENCES Products (product_ID)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET FOREIGN_KEY_CHECKS=1;
COMMIT;